# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.8'



#Define services
services:

  keycloak-beer:
    #hostname: keycloak-beer
    image: "quay.io/keycloak/keycloak:12.0.1"
    container_name: keycloak-beer
    #command: -Djboss.http.port=80
    volumes:
      - ${PWD}/keycloak/tmp/import:/tmp/import
    ports:
      - 10000:8080
    #Environment variable
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/import/beer-realm.json
      - KEYCLOAK_FRONTEND_URL='http://localhost:10000/auth'
    networks:
      - network-beer

  #Back-end Spring Boot Application
  backend-beer:
    #hostname: backend-beer
    image: local/${BACKEND_FOLDER}
    build:
      context: ./${BACKEND_FOLDER}
      dockerfile: ./Dockerfile
    container_name: backend-beer
    #Environment variables for Spring Boot Application.
#    environment:
#      - DB_SERVER=scrum-postgres
    ports:
      - 11000:8081
    depends_on:
      - keycloak-beer
    networks:
      - network-beer

  #Fron-end Angular Application
  frontend-beer:
    #hostname: frontend-beer
    image: local/${FRONTEND_FOLDER}
    build:
      context: ./${FRONTEND_FOLDER}
      dockerfile: ./Dockerfile
    container_name: frontend-beer
    ports:
      - 4200:80
    depends_on:
      - keycloak-beer
      - backend-beer
    networks:
      - network-beer

#Volumes
#volumes:
#  keycloak-realm:
#    driver_opts:
#      type: none
#      device: ${PWD}/keycloak/tmp/import
#      o: bind

networks:
  network-beer:
    name: network-beer