apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-beer
  name: backend-beer
spec:
  ports:
  - name: "11000"
    port: 11000
    targetPort: 8081
  selector:
    io.kompose.service: backend-beer
status:
  loadBalancer: {}
