apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-beer
  name: frontend-beer
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 80
  selector:
    io.kompose.service: frontend-beer
status:
  loadBalancer: {}
