apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak-beer
  name: keycloak-beer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak-beer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: keycloak-beer
    spec:
      containers:
      - env:
        - name: KEYCLOAK_FRONTEND_URL
          value: '''http://localhost:10000/auth'''
        - name: KEYCLOAK_IMPORT
          value: /tmp/import/beer-realm.json
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: KEYCLOAK_USER
          value: admin
        image: quay.io/keycloak/keycloak:12.0.1
        imagePullPolicy: ""
        name: keycloak-beer
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /tmp/import
          name: cdrive
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: cdrive
        persistentVolumeClaim:
          claimName: cdrive
status: {}
