apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak-beer
  name: keycloak-beer
spec:
  ports:
  - name: "10000"
    port: 10000
    targetPort: 8080
  selector:
    io.kompose.service: keycloak-beer
status:
  loadBalancer: {}
